services:
  perl:
    build: .
    image: training-perl:local
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    command: morbo -l http://0.0.0.0:3000 app.pl
